name: Build PDFRenamer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            git
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-pkg-config

      - name: Configure
        run: |
          cmake -B build -G Ninja

      - name: Build
        run: |
          cmake --build build -j4

      - name: Check Qt tools
        run: |
          echo "===== PATH ====="
          echo $PATH

          echo
          echo "===== Searching for windeployqt ====="
          which windeployqt || true
          find /mingw64 -name "windeployqt.exe" 2>/dev/null || true

          echo
          echo "===== Searching for qmake ====="
          which qmake || true
          find /mingw64 -name "qmake*" 2>/dev/null || true

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PDFRenamer
          path: build/PDFRenamer.exe