name: Build PDFRenamer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            git
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-pkg-config
            p7zip

      - name: Configure
        run: |
          cmake -B build -G Ninja

      - name: Build
        run: |
          cmake --build build -j4

      - name: Create portable package
        run: |
          mkdir -p portable
          mkdir -p portable/Runtime/LibreOffice

          cp build/PDFRenamer.exe portable/

          echo "===== Copy ALL DLL ====="
          find /mingw64/bin -maxdepth 1 -name "*.dll" -exec cp {} portable/ \;

          echo "===== Copy Qt Plugins ====="

          mkdir -p portable/platforms
          mkdir -p portable/styles
          mkdir -p portable/imageformats
          mkdir -p portable/iconengines

          cp -r /mingw64/share/qt5/plugins/platforms/* portable/platforms/ 2>/dev/null || true
          cp -r /mingw64/share/qt5/plugins/styles/* portable/styles/ 2>/dev/null || true
          cp -r /mingw64/share/qt5/plugins/imageformats/* portable/imageformats/ 2>/dev/null || true
          cp -r /mingw64/share/qt5/plugins/iconengines/* portable/iconengines/ 2>/dev/null || true

          echo
          echo "===== Portable content ====="
          find portable

      - name: Create ZIP
        run: |
          cd portable
          7z a ../PDFRenamer_Portable.zip *

      - name: Upload Portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: PDFRenamer_Portable
          path: PDFRenamer_Portable.zip